CREATE DATABASE DB_GESTOR_DE_BIBLIOTECA;

USE DB_GESTOR_DE_BIBLIOTECA;

CREATE TABLE Usuarios (
    ID INT PRIMARY KEY IDENTITY,
    Nombre NVARCHAR(100) NOT NULL,
    Apellido NVARCHAR(100) NOT NULL,
    DNI NVARCHAR(10) NOT NULL UNIQUE,
    Telefono NVARCHAR(15),
    Email NVARCHAR(100) NOT NULL,
    Imagen NVARCHAR(255), 
    Suspendido BIT DEFAULT 0
);
GO
CREATE TABLE Libros (
    ID INT PRIMARY KEY IDENTITY,
    Titulo NVARCHAR(255) NOT NULL,
    Autor NVARCHAR(255),
    Imagen NVARCHAR(255),
    Stock INT NOT NULL DEFAULT 0,
    Fecha_Publicacion DATE
);
GO
CREATE TABLE Prestamos (
    ID INT PRIMARY KEY IDENTITY,
    ID_Usuario INT NOT NULL,
    ID_Libro INT NOT NULL,
    Fecha_Prestamo DATETIME NOT NULL,
    Fecha_Devolucion DATETIME NOT NULL,
    Devuelto BIT DEFAULT 0,
    CONSTRAINT FK_Prestamo_Usuario FOREIGN KEY (ID_Usuario) REFERENCES Usuarios(ID),
    CONSTRAINT FK_Prestamo_Libro FOREIGN KEY (ID_Libro) REFERENCES Libros(ID)
);
GO
CREATE TABLE Suspensiones (
    ID INT PRIMARY KEY IDENTITY,
    ID_Usuario INT NOT NULL,
    Fecha_Suspension DATETIME NOT NULL,
    CONSTRAINT FK_Suspension_Usuario FOREIGN KEY (ID_Usuario) REFERENCES Usuarios(ID)
);

